server:
  port: 7070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root
    password: root123
    #driver-class-name: com.mysql.cj.jdbc.Driver

#JPA CONFIGURATION

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update
    show-sql: true

  application-name: PRODUCT-SERVICE